/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./scenee.glb --types
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props: JSX.IntrinsicElements["group"]) {
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	const { nodes, materials } = useGLTF("/scene.glb") as any;
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Plane001.geometry} material={materials["Material.001"]} />
			<group position={[-2.039, 0.417, -0.68]} rotation={[-Math.PI / 2, 0, 0]} scale={1.426}>
				<mesh geometry={nodes.Cube018.geometry} material={materials["WRITINGCOOLHEROES.001"]} />
				<mesh geometry={nodes.Cube018_1.geometry} material={materials["PAPER.001"]} />
				<mesh geometry={nodes.Cube018_2.geometry} material={materials.EYESEEYOU} />
				<mesh
					geometry={nodes.Cube018_3.geometry}
					material={materials["THECHEMISTRYOFDEPRESSION.001"]}
				/>
				<mesh geometry={nodes.Cube018_4.geometry} material={materials.TUBERCULUS} />
			</group>
			<mesh
				geometry={nodes.Plane003.geometry}
				material={materials["Material.003"]}
				position={[-0.4, 0, 0.06]}
				scale={[1.809, 1, 2.372]}
			/>
			<group position={[-2.012, 0.494, -0.163]} rotation={[-1.547, 1.241, 1.546]}>
				<mesh geometry={nodes.Mesh.geometry} material={materials["Plastic_black glossy"]} />
				<mesh geometry={nodes.Mesh_1.geometry} material={materials.Screen} />
				<mesh geometry={nodes.Mesh_2.geometry} material={materials.Metal_aluminum} />
				<group position={[0, -0.08, -0.028]} rotation={[0.33, 0, 0]}>
					<mesh geometry={nodes.Mesh001.geometry} material={materials["Plastic_black textured"]} />
					<mesh geometry={nodes.Mesh001_1.geometry} material={materials["Plastic_black glossy"]} />
					<mesh geometry={nodes.Mesh001_2.geometry} material={materials["Braided cable_PBR_glb"]} />
				</group>
				<mesh
					geometry={nodes["3"].geometry}
					material={materials.Metal_Chrome}
					position={[-0.013, -0.083, -0.029]}
					rotation={[0.33, 0, 0]}
				/>
			</group>
			<mesh
				geometry={nodes.Cube001.geometry}
				material={materials["Material.001"]}
				position={[-2.006, 0.211, 0.44]}
				scale={[0.193, 0.158, 0.143]}
			/>
			<mesh
				geometry={nodes.Cube002.geometry}
				material={materials["Material.001"]}
				position={[-2.025, 0.237, 0.44]}
				scale={[0.193, 0.158, 0.143]}
			/>
			<mesh
				geometry={nodes.Cube003.geometry}
				material={materials["Material.001"]}
				position={[-2.006, 0.237, 0.44]}
				scale={[0.193, 0.158, 0.143]}
			/>
			<mesh
				geometry={nodes.Cube004.geometry}
				material={materials["Material.001"]}
				position={[-2.006, 0.237, 0.44]}
				scale={[0.193, 0.158, 0.143]}
			/>
			<mesh
				geometry={nodes.Cube005.geometry}
				material={materials["Material.001"]}
				position={[-2.017, 0.238, 0.585]}
			/>
			<mesh
				geometry={nodes.Cube006.geometry}
				material={materials["Material.001"]}
				position={[-2.017, 0.238, -0.459]}
			/>
			<mesh
				geometry={nodes.Cube007.geometry}
				material={materials["Material.001"]}
				position={[-2.006, 0.237, 0.44]}
				scale={[0.193, 0.158, 0.143]}
			/>
			<mesh
				geometry={nodes.Cube008.geometry}
				material={materials["Material.006"]}
				position={[-1.977, 0.175, -0.144]}
				rotation={[0, Math.PI / 2, 0]}
				scale={0.048}
			/>
			<group
				position={[-1.979, 0.188, -0.393]}
				rotation={[-0.449, 0, Math.PI / 2]}
				scale={[0.086, 0.145, 0.006]}
			>
				<mesh geometry={nodes.Cube011.geometry} material={materials.PAPER} />
				<mesh geometry={nodes.Cube011_1.geometry} material={materials.THEARTOF} />
				<mesh geometry={nodes.Cube011_2.geometry} material={materials.Themurderof} />
				<mesh geometry={nodes.Cube011_3.geometry} material={materials.DOSHEEPDREAM} />
			</group>
			<mesh
				geometry={nodes.Component25001.geometry}
				material={materials["集简空间m210109-05723.001"]}
				position={[-2.04, 0.497, -0.82]}
				rotation={[-0.091, 1.016, 0.098]}
				scale={0}
			/>
			<group
				position={[-1.964, 0.122, -0.246]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[0.069, 0.116, 0.004]}
			>
				<mesh geometry={nodes.Cube017.geometry} material={materials["NOEVENSTARSLAST.001"]} />
				<mesh geometry={nodes.Cube017_1.geometry} material={materials["PAPER.006"]} />
				<mesh geometry={nodes.Cube017_2.geometry} material={materials["HATSGUNS.001"]} />
				<mesh geometry={nodes.Cube017_3.geometry} material={materials["REDCORE.001"]} />
				<mesh geometry={nodes.Cube017_4.geometry} material={materials["TRUELIAR.001"]} />
			</group>
			<mesh geometry={nodes.Plane004.geometry} material={materials["Material.001"]} />
			<mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} />
			<mesh
				geometry={nodes.Plane006.geometry}
				material={materials["Material.001"]}
				position={[-2.058, 1.93, -1.319]}
			/>
			<group
				position={[-2.045, 1.106, -1.465]}
				rotation={[-0.449, 0, Math.PI / 2]}
				scale={[0.086, 0.145, 0.006]}
			>
				<mesh geometry={nodes.Cube014.geometry} material={materials.PAPER} />
				<mesh geometry={nodes.Cube014_1.geometry} material={materials.THEARTOF} />
				<mesh geometry={nodes.Cube014_2.geometry} material={materials.Themurderof} />
				<mesh geometry={nodes.Cube014_3.geometry} material={materials.DOSHEEPDREAM} />
			</group>
			<group position={[-2.007, 0.541, 0.44]} scale={0.116}>
				<mesh geometry={nodes["G-__555564_1"].geometry} material={materials["gold ss"]} />
				<mesh geometry={nodes["G-__555564_2"].geometry} material={materials.heiqi1} />
				<mesh geometry={nodes["G-__555564_3"].geometry} material={materials["[0132_LightGray]"]} />
			</group>
			<group position={[-2.083, 0.188, -1.328]} rotation={[-Math.PI / 2, 0, 1.745]} scale={-0.013}>
				<mesh
					geometry={nodes["Assembly~17_Defintion_1"].geometry}
					material={materials["Material #1"]}
				/>
				<mesh
					geometry={nodes["Assembly~17_Defintion_2"].geometry}
					material={materials["Material #21474248082.001"]}
				/>
			</group>
			<mesh
				geometry={nodes.Plant_24_Plant_24002.geometry}
				material={materials.wire_088177027}
				position={[-1.734, 0, 0.983]}
				scale={1.707}
			/>
			<mesh
				geometry={nodes.Decor_04_Decor_04001.geometry}
				material={materials.Archisketch_LEON_Books_Frame}
				position={[-2.055, 1.481, -1.309]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={1.072}
			/>
			<mesh
				geometry={nodes.Vase_01_Vase_01001.geometry}
				material={materials["initialShadingGroup.030"]}
				position={[-2.055, 1.006, -1.235]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={0.731}
			/>
			<mesh
				geometry={nodes.Vase_02_Vase_02001.geometry}
				material={materials["initialShadingGroup.031"]}
				position={[-2.044, 0.53, -1.329]}
				rotation={[Math.PI, 0, Math.PI]}
				scale={1.044}
			/>
			<mesh
				geometry={nodes.Plane.geometry}
				material={nodes.Plane.material}
				position={[-2.19, 1, -0.24]}
				rotation={[0, 0, Math.PI / 2]}
			/>
		</group>
	);
}

useGLTF.preload("/scene.glb");
